/**
 * pnpm mage-inversion:gen — regenerate packages/sim/src/mage-decks-flood.ts from docs/mage-inversion-lists.md
 * (S42b; the `flood:gen` pattern: the document is the source, the table is generated, and
 * s42b-mage-inversion.test.ts pins them together). Fails loudly on an unknown card name, a mage the cleansheet
 * does not know, a list that is not 40 / 17, a gold or prizeOnly card, or a card outside the heading's pair.
 * `primaryColors` is the PIP order of the list (ties to the kept colour — the one the phase-one list shares).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { loadCardPool } from "@shandalar/cards/loader";
import { MAGE_DECKS, parseMageInversionLists } from "@shandalar/sim/mage-decks";

/** The flood lists' AI archetypes (the document names the plan, not the weight table — S42b interim, logged in
 * the handoff for the planner): what the forty is built to do. */
const ARCHETYPE: Record<string, "aggro" | "midrange" | "control"> = {
  vael: "midrange", kessa: "control", maelin: "midrange", brennor: "aggro", pell: "midrange",
  corvane: "midrange", varro: "control", sorrel: "aggro", ysolde: "aggro", quill: "midrange",
};

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "../../..");
const pool = loadCardPool(join(ROOT, "data/cards")).cards;
const idOf = new Map([...pool.values()].map((d) => [d.name, d.id]));
const lists = parseMageInversionLists(readFileSync(join(ROOT, "docs/mage-inversion-lists.md"), "utf8"), (n) => idOf.get(n));
if (lists.length !== 10) throw new Error(`mage-inversion:gen — the document has ${lists.length} lists; the inversion is ten`);

const rows: string[] = [];
for (const l of lists) {
  const key = Object.keys(MAGE_DECKS).find((k) => MAGE_DECKS[k]!.name === l.name);
  if (!key) throw new Error(`mage-inversion:gen — no mage named "${l.name}"`);
  const base = MAGE_DECKS[key]!;
  if (base.tier === 1) throw new Error(`mage-inversion:gen — ${l.name} is tier 1; tier 1 does not invert`);
  const kept = [...l.pair].filter((c) => base.colors.includes(c));
  if (kept.length !== 1) throw new Error(`mage-inversion:gen — ${l.name}: ${base.colors} → ${l.pair} must keep exactly one colour`);
  const colors = kept[0]! + [...l.pair].find((c) => c !== kept[0])!;
  let total = 0, lands = 0;
  const pips: Record<string, number> = { W: 0, U: 0, B: 0, R: 0, G: 0 };
  for (const e of l.decklist) {
    const def = pool.get(e.cardId)!;
    total += e.count;
    if (def.types.includes("Land")) lands += e.count;
    if (def.prizeOnly) throw new Error(`mage-inversion:gen — ${l.name}: ${def.name} is prizeOnly`);
    const cs = new Set((def.manaCost ?? "").match(/[WUBRG]/g) ?? []);
    if (cs.size > 1) throw new Error(`mage-inversion:gen — ${l.name}: ${def.name} is gold`);
    for (const c of cs) if (!colors.includes(c)) throw new Error(`mage-inversion:gen — ${l.name}: ${def.name} is outside ${l.pair}`);
    for (const c of Object.keys(pips)) pips[c]! += e.count * ((def.manaCost ?? "").match(new RegExp(`\\{${c}\\}`, "g")) ?? []).length;
  }
  if (total !== 40 || lands !== 17) throw new Error(`mage-inversion:gen — ${l.name}: ${total} cards / ${lands} lands; a flood list is 40 / 17`);
  const primaryColors = [...colors].sort((a, b) => pips[b]! - pips[a]!).join("");
  rows.push(`  ${key}: { colors: ${JSON.stringify(colors)}, primaryColors: ${JSON.stringify(primaryColors)}, archetype: ${JSON.stringify(ARCHETYPE[key])}, decklist: d([${l.decklist.map((e) => `[${JSON.stringify(e.cardId)}, ${e.count}]`).join(", ")}]) },`);
  console.log(`${l.name}: ${base.colors} → ${colors} (pips ${primaryColors}: ${[...colors].map((c) => `${c}${pips[c]}`).join(" ")})`);
}

const out = `// GENERATED by \`pnpm mage-inversion:gen\` from docs/mage-inversion-lists.md — do not edit by hand (S42b).
import type { MageFloodList, MageDecklist } from "./mage-decks.js";

const d = (pairs: [string, number][]): MageDecklist => pairs.map(([cardId, count]) => ({ cardId, count }));

/** The ten tier-2/3 mages' phase-two lists (the still pairs), by mage key. \`colors\` is kept-colour-first. */
export const MAGE_FLOOD_LISTS: Record<string, MageFloodList> = {
${rows.join("\n")}
};
`;
writeFileSync(join(ROOT, "packages/sim/src/mage-decks-flood.ts"), out);
console.log("mage-inversion:gen — ten lists written");
