/**
 * pnpm open:gen — S46 (ADR-142/143): the Open's twelve lists from the planner's document (+ the brief's amendments and
 * the Loop, declared in @shandalar/sim/open-lists) → `packages/sim/src/open-decks.ts` (committed; pinned by
 * open-lists.test.ts) and the Lab's `analysis/decks/open-<key>.json` (local). Every list is checked against the Open.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { loadCardPool } from "@shandalar/cards/loader";
import { buildLoop, parseOpenLists } from "@shandalar/sim/open-lists";
import { checkDeck } from "./legality.js";
import { OPEN_FORMAT } from "./formats.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "../../..");
const pool = loadCardPool(join(ROOT, "data/cards")).cards;
const idOf = new Map([...pool.values()].map((d) => [d.name, d.id]));
const lists = parseOpenLists(readFileSync(join(ROOT, "docs/convocation/convocation-open-lists-draft-2.md"), "utf8"), (n) => idOf.get(n));
if (lists.length !== 11) throw new Error(`open:gen — the document has ${lists.length} lists; the Open's seed is eleven`);
lists.push(buildLoop(lists.find((l) => l.key === "coin")!, (n) => idOf.get(n)));
// Post-S53 (Chris): the lists contributed from play (data/convocation/open-contributed.json), after the twelve
const contributed = (JSON.parse(readFileSync(join(ROOT, "data/convocation/open-contributed.json"), "utf8")) as { lists: { key: string; name: string; title: string; archetype: "aggro" | "midrange" | "control"; decklist: { cardId: string; count: number }[] }[] }).lists;
for (const c of contributed) {
  if (lists.some((l) => l.key === c.key)) throw new Error(`open:gen — a contributed list reuses the key ${c.key}`);
  for (const e of c.decklist) if (!pool.has(e.cardId)) throw new Error(`open:gen — ${c.key} names ${e.cardId}, not in the pool`);
  lists.push({ key: c.key, name: c.name, title: c.title, archetype: c.archetype, decklist: c.decklist.map((e) => ({ ...e })) } as never);
}
for (const l of lists) {
  const n = l.decklist.reduce((s, e) => s + e.count, 0);
  if (n !== 60) throw new Error(`open:gen — ${l.key} has ${n} cards`);
  const c = checkDeck(l.decklist, null, OPEN_FORMAT.rule, pool);
  if (!c.ok) throw new Error(`open:gen — ${l.key} fails the Open: ${c.problems.join("; ")}`);
}
const body = lists.map((l) => `  ${l.key}: { key: ${JSON.stringify(l.key)}, name: ${JSON.stringify(l.name)}, title: ${JSON.stringify(l.title)}, archetype: ${JSON.stringify(l.archetype)}, decklist: d([${l.decklist.map((e) => `[${JSON.stringify(e.cardId)}, ${e.count}]`).join(", ")}]) },`).join("\n");
writeFileSync(join(ROOT, "packages/sim/src/open-decks.ts"), `// GENERATED by \`pnpm open:gen\` from docs/convocation/convocation-open-lists-draft-2.md + the S46 amendments + data/convocation/open-contributed.json — do not edit by hand.
import type { OpenList, OpenDecklist } from "./open-lists.js";

const d = (pairs: [string, number][]): OpenDecklist => pairs.map(([cardId, count]) => ({ cardId, count }));

/** S46 (ADR-142/143): the Open's twelve seed lists, then (post-S53) the lists contributed from play, by key. */
export const OPEN_DECKS: Record<string, OpenList> = {
${body}
};
`);
mkdirSync(join(ROOT, "analysis/decks"), { recursive: true });
for (const l of lists) writeFileSync(join(ROOT, `analysis/decks/open-${l.key}.json`), JSON.stringify({ name: `open-${l.key} (${l.name})`, archetype: l.archetype, decklist: l.decklist, basedOn: "docs/convocation/convocation-open-lists-draft-2.md + S46", notes: l.title }, null, 2) + "\n");
console.log(`open:gen — ${lists.length} lists, each 60 and legal in the Open: ${lists.map((l) => l.key).join(", ")}`);
