/**
 * S58 (ADR-169): docs/reference/open-lists.md — every Open list as it stands, generated by `pnpm open:gen` from the
 * lists' own sources (data/convocation/open-seeds.json, sim/open-lists.ts, data/convocation/open-contributed.json) and
 * sync-tested: its sixty, its fifteen, its plan, its revisions by session, its mean on the table of record.
 */
import type { CardDef } from "@shandalar/cards";
import type { ComboPlan } from "@shandalar/agents";
import type { OpenList, OpenRevision } from "@shandalar/sim/open-lists";

export interface OpenReferenceInput {
  lists: readonly OpenList[];
  cards: Map<string, CardDef>;
  plans: readonly ComboPlan[];
  archived: Record<string, string>;
  /** `open:<key>` → the list's mean on the table of record. */
  means: Record<string, number>;
  amendments: Record<string, Record<string, number>>;
  revisions: readonly OpenRevision[];
  /** A contributed list's source line and its revision notes. */
  contributed: Record<string, { source?: string; revisions?: { session: string; note: string }[] }>;
}

/** ADR-170: the nonland cards (outside the restricted list's power) that more than half the active lists play. */
export function staples(lists: readonly OpenList[], cards: Map<string, CardDef>, skip: readonly string[] = []): { cardId: string; lists: number; copies: number }[] {
  const active = lists.filter((l) => !l.archived), by = new Map<string, { lists: number; copies: number }>();
  for (const l of active) for (const e of l.decklist) {
    if (cards.get(e.cardId)?.types.includes("Land") || skip.includes(e.cardId)) continue;
    const x = by.get(e.cardId) ?? { lists: 0, copies: 0 }; x.lists += 1; x.copies += e.count; by.set(e.cardId, x);
  }
  return [...by].filter(([, x]) => x.lists * 2 > active.length).map(([cardId, x]) => ({ cardId, ...x })).sort((a, b) => b.lists - a.lists || b.copies - a.copies || a.cardId.localeCompare(b.cardId));
}
/** The most-played nonland cards of the active lists (the watch list beside the staples). */
export function mostPlayed(lists: readonly OpenList[], cards: Map<string, CardDef>, skip: readonly string[], n: number): { cardId: string; lists: number; copies: number }[] {
  const active = lists.filter((l) => !l.archived), by = new Map<string, { lists: number; copies: number }>();
  for (const l of active) for (const e of l.decklist) {
    if (cards.get(e.cardId)?.types.includes("Land") || skip.includes(e.cardId)) continue;
    const x = by.get(e.cardId) ?? { lists: 0, copies: 0 }; x.lists += 1; x.copies += e.count; by.set(e.cardId, x);
  }
  return [...by].map(([cardId, x]) => ({ cardId, ...x })).sort((a, b) => b.lists - a.lists || b.copies - a.copies || a.cardId.localeCompare(b.cardId)).slice(0, n);
}

export function renderOpenListsReference(input: OpenReferenceInput, restricted: readonly string[]): string {
  const { lists, cards, plans, archived, means, amendments, revisions, contributed } = input;
  const name = (id: string) => cards.get(id)?.name ?? id;
  const line = (xs: { cardId: string; count: number }[]) => xs.map((e) => `${e.count} ${name(e.cardId)}`).join(" · ");
  const delta = (d: Record<string, number>) => { const out = Object.entries(d).filter(([, n]) => n < 0).map(([c, n]) => `−${-n} ${c}`), ins = Object.entries(d).filter(([, n]) => n > 0).map(([c, n]) => `+${n} ${c}`); return `${out.join(" ")} → ${ins.join(" ")}`; };
  const L: string[] = [];
  L.push("# The Open's lists", "", "*GENERATED by `pnpm open:gen` — do not edit by hand. The lists live in code (ADR-169): the seeds in `data/convocation/open-seeds.json`, their revisions in `packages/sim/src/open-lists.ts`, the lists contributed from play, the archive, the plans and the registered fifteens in `data/convocation/open-contributed.json`.*", "");
  const active = lists.filter((l) => !l.archived);
  L.push("## The table of record", "", "A list's mean win rate against the other active lists (registered sixties, master both seats).", "", "| list | title | pilot | mean |", "|---|---|---|---|");
  for (const l of [...active].sort((a, b) => (means[`open:${b.key}`] ?? 0) - (means[`open:${a.key}`] ?? 0) || a.key.localeCompare(b.key))) L.push(`| ${l.name} | ${l.title} | ${l.archetype} | ${means[`open:${l.key}`] ?? "not yet measured"} |`);
  L.push("", `Archived (kept in the data, out of the field): ${lists.filter((l) => l.archived).map((l) => l.name).join(", ") || "none"}.`, "");
  const st = staples(lists, cards, restricted);
  L.push("## Staples (ADR-170)", "", `Nonland cards outside the restricted list that more than half of the ${active.length} active lists play: ${st.length ? st.map((s) => `${name(s.cardId)} (${s.lists} lists, ${s.copies} copies)`).join("; ") : "none"}.`, "", `The most played: ${mostPlayed(lists, cards, restricted, 8).map((s) => `${name(s.cardId)} ${s.lists}`).join(" · ")}.`, "");
  for (const l of lists) {
    const def = (id: string) => cards.get(id)!;
    const lands = l.decklist.filter((e) => def(e.cardId).types.includes("Land")), creatures = l.decklist.filter((e) => !def(e.cardId).types.includes("Land") && def(e.cardId).types.includes("Creature")), other = l.decklist.filter((e) => !def(e.cardId).types.includes("Land") && !def(e.cardId).types.includes("Creature"));
    const n = (xs: { count: number }[]) => xs.reduce((a, e) => a + e.count, 0);
    L.push(`## ${l.name} — ${l.title}`, "", `\`${l.key}\` · ${l.archetype}${l.archived ? " · **archived**" : ` · mean ${means[`open:${l.key}`] ?? "not yet measured"}`}`, "");
    if (l.archived) L.push(`*Archived:* ${archived[l.key] ?? ""}`, "");
    L.push(`- **Lands (${n(lands)}):** ${line(lands)}`, `- **Creatures (${n(creatures)}):** ${line(creatures) || "—"}`, `- **Other (${n(other)}):** ${line(other) || "—"}`);
    L.push(l.sideboard ? `- **Its fifteen (registered):** ${line(l.sideboard)}` : "- **Its fifteen:** built by the field's builder for each seat (none registered).");
    const plan = plans.find((p) => p.key === l.key);
    if (plan) L.push(`- **Its plan** (${plan.goal ?? "loop"}): ${(plan.pieces ?? [plan.piece]).map(name).join(" or ")}; set up by ${plan.setup.map((s) => name(s.card)).join(", ")}; started by ${plan.start.map((s) => name(s.card)).join(", ")}; dig ${plan.dig.map(name).join(", ") || "—"}; fuel ${plan.fuel.map(name).join(", ") || "—"}.`);
    const hist: string[] = [];
    const c = contributed[l.key];
    if (c?.source) hist.push(`contributed — ${c.source}`);
    if (!c && l.key !== "loop") hist.push("a planner's seed list (2026-09-30)");
    if (l.key === "loop") hist.push("the twelfth list (S46): built from the Coin");
    if (amendments[l.key]) hist.push(`S46 and after: ${delta(amendments[l.key]!)}`);
    for (const r of revisions) if (r.lists[l.key]) hist.push(`${r.session}: ${delta(r.lists[l.key]!)}${r.why?.[l.key] ? ` (${r.why[l.key]})` : ""}`);
    for (const r of c?.revisions ?? []) hist.push(`${r.session}: ${r.note}`);
    L.push("- **History:**", ...hist.map((h) => `  - ${h}`), "");
  }
  return L.join("\n");
}
