/**
 * Deploy playtest r1 (Chris, 2026-09-04): the STANDING REFERENCE — generated documents that say what
 * is implemented right now, for the planner's fresh read (tuning passes, diversification of the
 * early decklists). Two renderers: the card pool (every non-token def with its text, tier and price)
 * and the enemies (every opponent the player can meet, with its starting life and decklist).
 * `pnpm reference` writes docs/reference/*.md; a sync test pins the files to the renderers (the
 * knobs.md precedent, principle 11).
 */
import type { CardDef } from "@shandalar/cards";
import { manaValue, parseManaCost } from "@shandalar/cards";
import { DECKS, DECK_ARCHETYPES, type DeckKey } from "@shandalar/sim/decks";
import { EXPANSION_DECKS } from "@shandalar/sim/expansion-decks";
import { COURT_DECKS } from "@shandalar/sim/court-decks";
import { GUARDIAN_DECKS } from "@shandalar/sim/guardian-decks";
import { LORD_DECKS } from "@shandalar/sim/lord-decks";
import { COROLLA_DECKS } from "@shandalar/sim/corolla-decks";
import { HEART_DECK } from "@shandalar/sim/heart-deck";
import { enemyDeck, type Catalog, type OpponentDeckRef } from "./catalog.js";
import { DIFFICULTIES, resolveKnobs, type KnobValues } from "./knobs.js";
import { shopPrice } from "./shop.js";

type Decklist = { cardId: string; count: number }[];
export type OracleText = Record<string, { oracle_text?: string }>;

const colourOf = (d: CardDef): string =>
  d.colors && d.colors.length ? d.colors.join("") : (d.manaCost ?? "").replace(/[^WUBRG]/g, "").split("").filter((c, i, a) => a.indexOf(c) === i).join("") || "C";
const mv = (d: CardDef | undefined): number => (d ? manaValue(parseManaCost(d.manaCost ?? "")) : 0);
const cell = (s: string): string => s.replace(/\|/g, "\\|").replace(/\n/g, " ");

/** The card pool as one table: colour → mana value → name. Tokens and test cards excluded; laws included. */
export function renderCardsReference(pool: Map<string, CardDef>, knobs: KnobValues, oracle: OracleText = {}): string {
  const cards = [...pool.values()].filter((d) => !d.id.startsWith("test_") && !d.isTokenDef);
  cards.sort((a, b) => colourOf(a).localeCompare(colourOf(b)) || mv(a) - mv(b) || a.name.localeCompare(b.name));
  const rows = cards.map((d) => {
    const isBasic = d.types.includes("Land") && (d.supertypes ?? []).includes("Basic");
    const price = isBasic ? "free" : String(shopPrice(d, knobs));
    const tier = d.shopTier === undefined ? "1" : String(d.shopTier);
    const pt = d.power !== undefined && d.toughness !== undefined ? `${d.power}/${d.toughness}` : "";
    const flags = [d.prizeOnly ? "prizeOnly" : "", d.source === "custom" ? "custom" : "", d.law ? "law" : "", d.uncastable ? "uncastable" : ""].filter(Boolean).join(", ");
    const text = d.text ?? oracle[d.id]?.oracle_text ?? "";
    const type = `${(d.supertypes ?? []).join(" ")} ${d.types.join(" ")}`.trim() + (d.subtypes?.length ? ` — ${d.subtypes.join(" ")}` : "");
    return `| ${cell(d.name)} | ${colourOf(d)} | ${cell(type)} | ${d.manaCost || "—"} | ${mv(d)} | ${pt} | ${(d.keywords ?? []).join(", ")} | ${tier} | ${price} | ${flags} | ${cell(text)} |`;
  });
  const bySource = { real: cards.filter((d) => d.source !== "custom").length, custom: cards.filter((d) => d.source === "custom").length };
  return `# The card pool — standing reference

*Generated by \`pnpm reference\` from \`data/cards\` — do not edit by hand. ${cards.length} cards (${bySource.real} real, ${bySource.custom} custom; tokens excluded, the five laws included). Text is the def's \`text\` where authored, else the Scryfall oracle text from \`data/art/real/oracle.json\`. Shop tier: the ring a card first stocks in (1 civilized / 2 approach / 3 wild; R never stocks — the R drawer). Price = round(shopPriceMultiplier × shopBasePrice × (1 + mana value) × shopTierMultiplier[tier]) at default knobs (\`priceOverride\` where set); basics are free. \`prizeOnly\` cards never stock and are never staked. The pool-registry (docs/registries/pool-registry.md) carries each card's status and vocabulary words; the card-tier audit (docs/card-tier-audit-v2.md) carries the tiering rationale.*

| Card | Colour | Type | Cost | MV | P/T | Keywords | Tier | Price | Flags | Text |
|---|---|---|---|---|---|---|---|---|---|---|
${rows.join("\n")}
`;
}

function deckLines(decklist: Decklist, pool: Map<string, CardDef>): { list: string; total: number; lands: number; avgMv: string; colours: string } {
  const named = decklist.map((e) => ({ ...e, def: pool.get(e.cardId) }));
  const isLand = (d: CardDef | undefined) => !!d && d.types.includes("Land");
  const sorted = [...named].sort((a, b) => Number(isLand(b.def)) - Number(isLand(a.def)) || mv(a.def) - mv(b.def) || (a.def?.name ?? a.cardId).localeCompare(b.def?.name ?? b.cardId));
  const total = decklist.reduce((n, e) => n + e.count, 0);
  const lands = named.filter((e) => isLand(e.def)).reduce((n, e) => n + e.count, 0);
  const spells = named.filter((e) => !isLand(e.def));
  const spellCount = spells.reduce((n, e) => n + e.count, 0);
  const avgMv = spellCount ? (spells.reduce((s, e) => s + mv(e.def) * e.count, 0) / spellCount).toFixed(2) : "—";
  const colours = [...new Set(named.flatMap((e) => (e.def && !isLand(e.def) ? colourOf(e.def).split("") : [])))].filter((c) => c !== "C").sort().join("") || "C";
  return { list: sorted.map((e) => `${e.count} ${e.def?.name ?? e.cardId}`).join(" · "), total, lands, avgMv, colours };
}

/** Every enemy the player can meet, with how its starting life is set and its decklist. */
export function renderEnemiesReference(catalog: Catalog, pool: Map<string, CardDef>, knobs: KnobValues): string {
  const out: string[] = [];
  const std = knobs;
  const easy = resolveKnobs({ difficulty: DIFFICULTIES.easy });
  const hard = resolveKnobs({ difficulty: DIFFICULTIES.hard });
  const tri = (k: keyof KnobValues) => `${JSON.stringify(std[k])} (easy ${JSON.stringify(easy[k])} / hard ${JSON.stringify(hard[k])})`;

  out.push(`# The enemies — standing reference

*Generated by \`pnpm reference\` from \`data/world\` and the sim deck tables — do not edit by hand. Every opponent the player can fight, grouped by where it is met, with its STARTING LIFE (how it is set, at default knobs; the difficulty bundles in brackets) and its decklist (lands first, then by mana value). Deck stats: cards / lands / average mana value of the nonland cards / colours. AI profile = the heuristic ladder rung the opponent plays at (apprentice / journeyman / master). Knob values are the current registry defaults (docs/knobs.md).*

## How starting life is set

| Class | Starting life | Deck | AI profile |
|---|---|---|---|
| Roaming opponent (overworld; also the minion floors of every dungeon) | its \`worldLife\` (the catalog row); a LAIR resident fights at +\`lairResidentLifeBonus\` = ${tri("lairResidentLifeBonus")} | the catalog's deck ref (a slice deck, a beast deck, or a starter) | the row's difficulty |
| Mox-court guardian (the five Mox dungeons, civilized ring) | the dungeon's \`guardian.life\` + the empowerment tiers reached by steps walked inside (\`dungeonEmpowermentTiers\` = ${JSON.stringify(std.dungeonEmpowermentTiers)}) | COURT_DECKS by key | master |
| Power-dungeon guardian (the five approach-ring dungeons) | the dungeon's \`guardian.life\` + the same empowerment tiers | GUARDIAN_DECKS by key | master |
| Stronghold lord (the five seats, wild ring) | \`baseLife\` + growth − the spoke hunt's reduction: growth = min(\`lordGrowthCap\` ${tri("lordGrowthCap")}, floor(steps / \`lordGrowthSteps\` ${tri("lordGrowthSteps")}) × \`lordGrowthLife\` ${tri("lordGrowthLife")}); reduction = floor(spokeMinionPoints / \`spokePointsPerLife\` ${tri("spokePointsPerLife")}); never below \`lordLifeFloor\` ${tri("lordLifeFloor")}; + the stronghold's empowerment tiers (\`strongholdEmpowermentTiers\` = ${JSON.stringify(std.strongholdEmpowermentTiers)}) | LORD_DECKS by key | master |
| Petal court (the Corolla's five tips) | \`petalBossLife\` ${tri("petalBossLife")} (0 = the catalog's \`bossLife\` ${catalog.corolla?.bossLife ?? 30}); the Corolla's empowerment clock is shipped off (\`corollaEmpowermentTiers\` = ${JSON.stringify(std.corollaEmpowermentTiers)}) | COROLLA_DECKS by key | master |
| The Mirror (the Vault) | the player's own world life | a copy of the player's active deck + a Black Lotus | master |
| The Heart (the Manafleur) | \`heartLife\` ${tri("heartLife")} | HEART_DECK (sixty) | master |

Player-side constants for the same reads: \`startingWorldLife\` ${tri("startingWorldLife")}, \`anteCount\` ${tri("anteCount")} (the stake per duel), \`lossLifePenalty\` ${tri("lossLifePenalty")}.
`);

  // ---- roaming opponents ----
  const ops = [...catalog.opponents].sort((a, b) => (a.kind ?? "mage").localeCompare(b.kind ?? "mage") || a.tier - b.tier || (a.spoke ?? "").localeCompare(b.spoke ?? "") || a.name.localeCompare(b.name));
  out.push(`## Roaming opponents (${ops.length})

Mages roam anywhere; beasts are spoke-bound (their colour's ring). Tier 1 rolls in civilized rings, 2 in the approach, 3 in the wilds (the S18 spawn tables). The same templates staff the dungeons' minion floors by spoke.

| Opponent | Kind | Tier | Spoke | Life | AI profile | Deck | Cards / lands / avg MV / colours | Notes |
|---|---|---|---|---|---|---|---|---|`);
  const deckUsers = new Map<string, string[]>();
  for (const o of ops) {
    const d = enemyDeck(catalog, o.deck);
    const s = deckLines(d.decklist, pool);
    const notes = [o.buyable === false ? "not buyable" : "", o.knobs ? `knobs ${JSON.stringify(o.knobs)}` : ""].filter(Boolean).join("; ");
    out.push(`| ${o.name} | ${o.kind ?? "mage"} | ${o.tier} | ${o.spoke ?? "—"} | ${o.worldLife} | ${o.difficulty} | ${o.deck} (${d.archetype}) | ${s.total} / ${s.lands} / ${s.avgMv} / ${s.colours} | ${notes} |`);
    deckUsers.set(o.deck, [...(deckUsers.get(o.deck) ?? []), o.name]);
  }
  out.push(`\n### The roaming decklists (one entry per deck; who plays it)\n`);
  for (const [ref, users] of [...deckUsers.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
    const d = enemyDeck(catalog, ref as OpponentDeckRef);
    const s = deckLines(d.decklist, pool);
    const title = ref in DECKS ? `${DECKS[ref as DeckKey].name} (slice deck ${ref}, ${DECK_ARCHETYPES[ref as DeckKey]})` : ref.startsWith("beast:") ? `${EXPANSION_DECKS[ref.slice(6)]!.name} (${ref}, tier ${EXPANSION_DECKS[ref.slice(6)]!.tier}, ${d.archetype})` : `${ref} (${d.archetype})`;
    out.push(`- **${title}** — played by ${users.join(", ")} — ${s.total} cards, ${s.lands} lands, avg MV ${s.avgMv}\n  ${s.list}`);
  }

  // ---- the bosses ----
  const section = (title: string, intro: string, rows: { name: string; life: string; law?: string | undefined; extra?: string; decklist: Decklist; archetype: string }[]) => {
    out.push(`\n## ${title}\n\n${intro}\n`);
    for (const r of rows) {
      const s = deckLines(r.decklist, pool);
      out.push(`### ${r.name}\n\n- Starting life: ${r.life}\n${r.law ? `- Law: ${r.law}\n` : ""}${r.extra ? `- ${r.extra}\n` : ""}- Deck (${r.archetype}): ${s.total} cards, ${s.lands} lands, avg MV ${s.avgMv}, colours ${s.colours}\n  ${s.list}\n`);
    }
  };
  section("The Mox court (five Mox dungeons)", "The civilized ring's dungeons: a symmetric law at the door, the guardian at the deep end, a Mox and the guardian's card as the prize.",
    catalog.dungeons.map((m) => {
      const g = COURT_DECKS[m.guardian.key]!;
      return { name: `${m.guardian.name} — ${m.name} (${m.color})`, life: `${m.guardian.life} + empowerment`, law: `${m.law.name} — ${m.law.text}`, extra: `Prize: ${pool.get(m.prize.mox)?.name ?? m.prize.mox} + ${pool.get(m.prize.guardianCard)?.name ?? m.prize.guardianCard}`, decklist: g.decklist, archetype: g.archetype };
    }));
  section("The power-dungeon guardians (five approach-ring dungeons)", "The five legends; each teaches a power on defeat.",
    (catalog.powerDungeons ?? []).map((p) => {
      const g = GUARDIAN_DECKS[p.guardian.key]!;
      return { name: `${p.guardian.name} — ${p.name} (${p.color})`, life: `${p.guardian.life} + empowerment`, extra: `Prize: ${pool.get(p.prize.guardianCard)?.name ?? p.prize.guardianCard}; teaches: ${p.teaches}`, decklist: g.decklist, archetype: g.archetype };
    }));
  section("The stronghold lords (five seats)", "The wild ring's seats. The lord's partisan law sits on his side every battle inside; the lord duel adds his entrance.",
    (catalog.strongholdContent ?? []).map((c) => {
      const g = LORD_DECKS[c.lord.key]!;
      return { name: `${c.lord.name} — ${c.name} (${c.color})`, life: `base ${c.lord.baseLife} + growth − reduction (see above)`, law: `${c.law.name} — ${c.law.text}`, extra: `Card: ${pool.get(c.lord.cardId)?.name ?? c.lord.cardId}`, decklist: g.decklist, archetype: g.archetype };
    }));
  if (catalog.corolla) {
    const laws = new Map((catalog.strongholdContent ?? []).map((c) => [c.color, c.law]));
    section("The petal courts (the Corolla's five tips)", "Each tip fights under the RETURNED partisan law of the lord whose complement the pair is; win = the signature, both duals, the purse.",
      catalog.corolla.petals.map((p) => {
        const g = COROLLA_DECKS[p.boss.key]!;
        const law = laws.get(p.color);
        return { name: `${p.boss.name} — the ${p.color} petal (pair ${g.pair})`, life: `petalBossLife ${std.petalBossLife > 0 ? std.petalBossLife : (catalog.corolla?.bossLife ?? 30)}`, law: law ? `${law.name} — ${law.text}` : undefined, extra: `Prize: ${pool.get(p.signature)?.name ?? p.signature} + ${p.duals.map((d) => pool.get(d)?.name ?? d).join(" + ")}`, decklist: g.decklist, archetype: g.archetype };
      }));
    out.push(`\n## The Mirror (${catalog.corolla.vault.name})\n\n- Starting life: the player's own world life\n- Deck: a copy of the player's active deck plus one Black Lotus; the archetype is derived from the copy; ante off; master profile.\n`);
    if (catalog.corolla.heart) {
      const s = deckLines(HEART_DECK.decklist, pool);
      out.push(`\n## The Heart (${catalog.corolla.heart.boss.name})\n\n- Starting life: heartLife ${tri("heartLife")}\n- Ante: none (prizeOnly cards are never staked)\n- Deck (${HEART_DECK.archetype}): ${s.total} cards, ${s.lands} lands, avg MV ${s.avgMv}, colours ${s.colours}\n  ${s.list}\n`);
    }
  }

  // ---- the player's starters ----
  out.push(`\n## The player's starters (for the same read)\n`);
  for (const st of catalog.starters) {
    const s = deckLines(st.decklist, pool);
    const adj = (k: "easy" | "hard") => {
      const a = st[k];
      if (!a) return "";
      const add = (a.add ?? []).map((e) => `+${e.count} ${pool.get(e.cardId)?.name ?? e.cardId}`);
      const rem = (a.remove ?? []).map((e) => `−${e.count} ${pool.get(e.cardId)?.name ?? e.cardId}`);
      return `\n  ${k}: ${[...add, ...rem].join(", ") || "—"}`;
    };
    out.push(`- **${st.name}** (${st.color}, ${st.archetype}) — ${s.total} cards, ${s.lands} lands, avg MV ${s.avgMv}\n  ${s.list}${adj("easy")}${adj("hard")}`);
  }
  return out.join("\n") + "\n";
}
