// GENERATED by `pnpm open:gen` from the guides in data/convocation/open-contributed.json — do not edit by hand.
import type { SideboardGuide } from "./sideboard-ai.js";

/** S58 (Part 1): the guides authored with the Open's registered fifteens. */
export const SIDEBOARD_GUIDES: readonly SideboardGuide[] = [
 {
  "key": "locks",
  "fifteen": [
   {
    "cardId": "essence_scatter",
    "count": 3
   },
   {
    "cardId": "protocol",
    "count": 2
   },
   {
    "cardId": "serra_angel",
    "count": 2
   },
   {
    "cardId": "duress",
    "count": 2
   },
   {
    "cardId": "tormods_crypt",
    "count": 2
   },
   {
    "cardId": "faerie_macabre",
    "count": 2
   },
   {
    "cardId": "disenchant",
    "count": 2
   }
  ],
  "rows": [
   {
    "in": "protocol",
    "n": 2,
    "out": [
     "wrath_of_god"
    ],
    "when": [
     "fewLarge"
    ]
   },
   {
    "in": "serra_angel",
    "n": 2,
    "out": [
     "undermine",
     "absorb",
     "counterspell"
    ],
    "when": [
     "control"
    ]
   },
   {
    "in": "duress",
    "n": 2,
    "out": [
     "wrath_of_god",
     "swords_to_plowshares"
    ],
    "when": [
     "plan",
     "control"
    ]
   },
   {
    "in": "tormods_crypt",
    "n": 2,
    "out": [
     "serra_angel",
     "vindicate"
    ],
    "when": [
     "graveyard"
    ]
   },
   {
    "in": "faerie_macabre",
    "n": 2,
    "out": [
     "serra_angel",
     "vindicate"
    ],
    "when": [
     "graveyard"
    ]
   }
  ]
 },
 {
  "key": "reaper",
  "fifteen": [
   {
    "cardId": "tormods_crypt",
    "count": 3
   },
   {
    "cardId": "moss_viper",
    "count": 1
   },
   {
    "cardId": "deadly_recluse",
    "count": 1
   },
   {
    "cardId": "pyroclasm",
    "count": 3
   },
   {
    "cardId": "savage_twister",
    "count": 1
   },
   {
    "cardId": "char",
    "count": 2
   },
   {
    "cardId": "putrefy",
    "count": 4
   }
  ],
  "rows": [
   {
    "in": "tormods_crypt",
    "n": 3,
    "out": [
     "savage_twister",
     "lightning_bolt"
    ],
    "when": [
     "graveyard",
     "someGraveyard"
    ]
   },
   {
    "in": "char",
    "n": 2,
    "out": [
     "savage_twister"
    ],
    "when": [
     "control"
    ]
   },
   {
    "in": "deadly_recluse",
    "n": 1,
    "out": [
     "savage_twister"
    ],
    "when": [
     "control"
    ]
   },
   {
    "in": "putrefy",
    "n": 2,
    "out": [
     "lightning_bolt"
    ],
    "when": [
     "control"
    ]
   }
  ],
  "only": true
 }
];
