/**
 * Expansion 1 beast decklists (docs/expansion-1-cards-and-decks.md, planner-authored) as sim
 * infrastructure: fuzz/ladder coverage of the S17 batch in random and heuristic lines before the
 * S18 bestiary catalog adopts them. 30 cards each (ADR-077 amended ADR-074's 40 to 30).
 * S18: the world catalog references these as `beast:<key>` opponent decks (catalog.ts enemyDeck).
 */
export type ExpansionDecklist = { cardId: string; count: number }[];
const d = (pairs: [string, number][]): ExpansionDecklist => pairs.map(([cardId, count]) => ({ cardId, count }));

export const EXPANSION_DECKS: Record<string, { name: string; color: string; tier: 1 | 2 | 3; archetype: "aggro" | "midrange" | "control"; decklist: ExpansionDecklist }> = {
  grizzly: { name: "A Grizzly Bear", color: "G", tier: 1, archetype: "midrange", decklist: d([["forest", 13], ["grizzly_bears", 4], ["little_bear", 3], ["mother_bear", 2], ["werebear", 2], ["rumbling_baloth", 2], ["centaur_courser", 2], ["giant_growth", 2]]) },
  recluse: { name: "The Deadly Recluse", color: "G", tier: 1, archetype: "midrange", decklist: d([["forest", 13], ["deadly_recluse", 4], ["moss_viper", 3], ["treetop_snarespinner", 3], ["giant_growth", 3], ["prey_upon", 2], ["elvish_visionary", 2]]) },
  manowar: { name: "A Bloom of Man-o'-War", color: "U", tier: 1, archetype: "control", decklist: d([["island", 12], ["man_o_war", 4], ["mist_raven", 3], ["waterfront_bouncer", 2], ["boomerang", 3], ["essence_scatter", 2], ["wind_drake", 2], ["cloudkin_seer", 2]]) },
  tactician: { name: "The Cunning Tactician", color: "W", tier: 1, archetype: "aggro", decklist: d([["plains", 12], ["cunning_tactician", 4], ["master_decoy", 3], ["scepter_of_dominance", 2], ["fencing_ace", 3], ["savannah_lions", 2], ["raise_the_alarm", 2], ["pacifism", 2]]) },
  warband: { name: "The Boggart Warband", color: "R", tier: 2, archetype: "aggro", decklist: d([["mountain", 12], ["boggart_brute", 4], ["raging_goblin", 3], ["goblin_piker", 3], ["skirk_prospector", 2], ["hordeling_outburst", 2], ["goblin_chieftain", 2], ["goblin_grenade", 2]]) },
  // S20 (ADR-079, Chris-ruled): the 4× lifelink-deathtouch-flying core diluted to 3×, a removal spell traded
  // for a body (was 4 Nighthawk / 3 Child / 2 Rats / 2 Doom Blade). Identity intact, nut draws softened.
  nighthawk: { name: "A Vampire Nighthawk", color: "B", tier: 2, archetype: "midrange", decklist: d([["swamp", 12], ["vampire_nighthawk", 3], ["child_of_night", 4], ["typhoid_rats", 3], ["indulgent_aristocrat", 2], ["blood_artist", 2], ["doom_blade", 1], ["mind_rot", 2], ["tendrils_of_corruption", 1]]) },
  gale: { name: "The Living Gale", color: "U", tier: 2, archetype: "control", decklist: d([["island", 12], ["air_elemental", 3], ["wind_drake", 3], ["cloudkin_seer", 2], ["aven_fisher", 2], ["gravitational_shift", 2], ["aether_channeler", 2], ["counterspell", 2], ["boomerang", 2]]) },
  siegegang: { name: "The Siege-Gang", color: "R", tier: 3, archetype: "aggro", decklist: d([["mountain", 12], ["siege_gang_commander", 3], ["goblin_matron", 3], ["goblin_chieftain", 3], ["skirk_prospector", 2], ["hordeling_outburst", 2], ["boggart_brute", 2], ["goblin_grenade", 2], ["lightning_bolt", 1]]) },
  specter: { name: "The Hypnotic Specter", color: "B", tier: 3, archetype: "midrange", decklist: d([["swamp", 12], ["hypnotic_specter", 4], ["dark_ritual", 2], ["hymn_to_tourach", 2], ["duress", 2], ["waste_not", 2], ["doom_blade", 2], ["phyrexian_rager", 2], ["mind_rot", 1], ["tendrils_of_corruption", 1]]) },
  serra: { name: "The Serra Angel", color: "W", tier: 3, archetype: "control", decklist: d([["plains", 12], ["serra_angel", 3], ["youthful_valkyrie", 3], ["inspiring_overseer", 2], ["restoration_angel", 2], ["glorious_anthem", 2], ["swords_to_plowshares", 2], ["pacifism", 2], ["wrath_of_god", 1], ["raise_the_alarm", 1]]) },
  wurm: { name: "The Pelakka Wurm", color: "G", tier: 3, archetype: "midrange", decklist: d([["forest", 12], ["pelakka_wurm", 3], ["gaean_wurm", 3], ["baru_wurmspeaker", 2], ["llanowar_elves", 3], ["rampant_growth", 3], ["rumbling_baloth", 2], ["prey_upon", 2]]) },
  // S19 (ADR-078 / docs/bestiary-round-2.md): the grid-completing five.
  rats: { name: "A Plague of Rats", color: "B", tier: 1, archetype: "midrange", decklist: d([["swamp", 13], ["typhoid_rats", 4], ["child_of_night", 3], ["terror", 2], ["duress", 2], ["mind_rot", 2], ["phyrexian_rager", 2], ["gravedigger", 2]]) },
  ogre: { name: "A Gray Ogre", color: "R", tier: 1, archetype: "aggro", decklist: d([["mountain", 12], ["gray_ogre", 4], ["raging_goblin", 3], ["goblin_piker", 3], ["shock", 3], ["brute_force", 2], ["hill_giant", 2], ["blaze", 1]]) },
  lion: { name: "A Savannah Lion", color: "W", tier: 1, archetype: "aggro", decklist: d([["plains", 12], ["savannah_lions", 4], ["suntail_hawk", 4], ["fencing_ace", 3], ["master_decoy", 2], ["raise_the_alarm", 2], ["pacifism", 2], ["swords_to_plowshares", 1]]) },
  baloth: { name: "A Rumbling Baloth", color: "G", tier: 2, archetype: "midrange", decklist: d([["forest", 12], ["rumbling_baloth", 4], ["centaur_courser", 3], ["llanowar_elves", 3], ["grizzly_bears", 2], ["elvish_visionary", 2], ["giant_growth", 2], ["prey_upon", 2]]) },
  // S45 (ADR-140, the brief's lists verbatim): the tier-3 round — six beasts, thirty cards, twelve lands.
  dragonmage: { name: "The Dragon Mage", color: "R", tier: 3, archetype: "aggro", decklist: d([["mountain", 12], ["dragon_mage", 2], ["goblin_piker", 2], ["boggart_brute", 2], ["thundersnake", 1], ["arc_mage", 1], ["hordeling_outburst", 2], ["lightning_bolt", 3], ["shock", 2], ["blaze", 1], ["char", 1], ["pyroclasm", 1]]) },
  guttersnipe: { name: "The Guttersnipe", color: "R", tier: 3, archetype: "aggro", decklist: d([["mountain", 12], ["guttersnipe", 2], ["young_pyromancer", 2], ["arc_mage", 1], ["thundersnake", 1], ["lightning_bolt", 3], ["shock", 3], ["char", 1], ["blaze", 1], ["abrade", 2], ["brute_force", 1], ["hordeling_outburst", 1]]) },
  dreadpresence: { name: "The Dread Presence", color: "B", tier: 3, archetype: "midrange", decklist: d([["swamp", 11], ["thawing_glaciers", 1], ["dread_presence", 2], ["typhoid_rats", 2], ["child_of_night", 2], ["vampire_nighthawk", 1], ["phyrexian_rager", 2], ["gravedigger", 1], ["tendrils_of_corruption", 2], ["doom_blade", 2], ["terror", 1], ["diabolic_edict", 1], ["duress", 1], ["dark_ritual", 1]]) },
  emeria: { name: "The Emeria Angel", color: "W", tier: 3, archetype: "midrange", decklist: d([["plains", 11], ["evolving_wilds", 1], ["emeria_angel", 2], ["soul_warden", 2], ["suntail_hawk", 2], ["youthful_valkyrie", 2], ["inspiring_overseer", 1], ["master_decoy", 1], ["restoration_angel", 1], ["raise_the_alarm", 2], ["glorious_anthem", 1], ["pacifism", 2], ["swords_to_plowshares", 1], ["spirit_link", 1]]) },
  seedborn: { name: "The Seedborn Muse", color: "G", tier: 3, archetype: "midrange", decklist: d([["forest", 12], ["seedborn_muse", 2], ["llanowar_elves", 3], ["birds_of_paradise", 1], ["wood_elves", 2], ["grizzly_bears", 2], ["centaur_courser", 2], ["rumbling_baloth", 1], ["gaean_wurm", 1], ["giant_growth", 2], ["prey_upon", 1], ["rancor", 1]]) },
  tidewall: { name: "The Tidewall", color: "U", tier: 3, archetype: "control", decklist: d([["island", 12], ["tidewall", 2], ["wall_of_air", 2], ["hedron_crab", 2], ["traumatizer", 1], ["wind_drake", 1], ["thought_scour", 2], ["brainstorm", 2], ["counterspell", 2], ["essence_scatter", 1], ["boomerang", 2], ["altar_of_dementia", 1]]) },
  formation: { name: "The Faerie Formation", color: "U", tier: 3, archetype: "control", decklist: d([["island", 13], ["faerie_formation", 3], ["air_elemental", 2], ["gravitational_shift", 2], ["mist_raven", 2], ["wind_drake", 2], ["man_o_war", 2], ["essence_scatter", 2], ["counterspell", 1], ["control_magic", 1]]) },
};
