/**
 * S29 (ADR-099): THE MAGE CLEANSHEET — fifteen mage decks, one per named mage, rebuilt from the
 * planner's three cleansheet documents (docs/mage-cleansheet-tier{1,2,3}.md). Tier 1: five mono-colour
 * archetypes (apprentice, 8 life). Tier 2: the five flowing pairs as crosses of two parent lines
 * (journeyman, 10 life; two Ravnica duals). Tier 3: the same pairs, the other parents (master, 12 life,
 * anteCount 2; plus the pair's ABU dual). No gold cards, no prizeOnly cards (Reya Dawnbringer left
 * Corvane's list for a third Serra Angel — Chris, S29 kickoff). The catalog references these as
 * `mage:<key>`; the S5 slice decks A–E stay as sim/test infrastructure only.
 */
export type MageDecklist = { cardId: string; count: number }[];
const d = (pairs: [string, number][]): MageDecklist => pairs.map(([cardId, count]) => ({ cardId, count }));

export const MAGE_DECKS: Record<string, { opponentId: string; name: string; epithet: string; colors: string; tier: 1 | 2 | 3; archetype: "aggro" | "midrange" | "control"; decklist: MageDecklist }> = {
  oriel: { opponentId: "b1", name: "Sister Oriel", epithet: "the Almoner", colors: "W", tier: 1, archetype: "midrange", decklist: d([["plains", 15], ["secluded_steppe", 2], ["soul_warden", 4], ["suntail_hawk", 3], ["youthful_valkyrie", 3], ["inspiring_overseer", 2], ["master_decoy", 2], ["spirit_link", 2], ["pacifism", 2], ["raise_the_alarm", 2], ["swords_to_plowshares", 1], ["glorious_anthem", 1], ["restoration_angel", 1]]) },
  tessaly: { opponentId: "e1", name: "Tessaly Reed", epithet: "the Tidewright", colors: "U", tier: 1, archetype: "control", decklist: d([["island", 15], ["evolving_wilds", 2], ["hedron_crab", 4], ["cathartic_adept", 4], ["traumatizer", 3], ["brainstorm", 2], ["divination", 1], ["essence_scatter", 2], ["counterspell", 1], ["boomerang", 2], ["wind_drake", 2], ["altar_of_dementia", 2]]) },
  edric: { opponentId: "d1", name: "Pale Edric", epithet: "the Sexton", colors: "B", tier: 1, archetype: "midrange", decklist: d([["swamp", 15], ["barren_moor", 2], ["unearth", 3], ["zombify", 2], ["gravedigger", 3], ["gallows_djinn", 2], ["blood_artist", 2], ["indulgent_aristocrat", 2], ["phyrexian_rager", 2], ["child_of_night", 2], ["typhoid_rats", 2], ["terror", 2], ["dark_ritual", 1]]) },
  brann: { opponentId: "a1", name: "Brann the Scorched", epithet: "the Sparkwright", colors: "R", tier: 1, archetype: "aggro", decklist: d([["mountain", 15], ["forgotten_cave", 2], ["young_pyromancer", 3], ["arc_mage", 2], ["lightning_bolt", 3], ["shock", 3], ["abrade", 2], ["blaze", 2], ["brute_force", 2], ["hordeling_outburst", 2], ["goblin_piker", 2], ["thundersnake", 1], ["bonesplitter", 1]]) },
  hask: { opponentId: "c1", name: "Old Hask", epithet: "the Wardener", colors: "G", tier: 1, archetype: "aggro", decklist: d([["forest", 16], ["gladecover_scout", 4], ["blurred_mongoose", 3], ["birds_of_paradise", 2], ["rancor", 3], ["blanchwood_armor", 3], ["timberland_guide", 2], ["giant_growth", 3], ["prey_upon", 2], ["elvish_visionary", 2]]) },
  vael: { opponentId: "d2", name: "Mistress Vael", epithet: "the Tithe-Reeve", colors: "WB", tier: 2, archetype: "midrange", decklist: d([["plains", 8], ["swamp", 7], ["godless_shrine", 2], ["soul_warden", 3], ["suntail_hawk", 2], ["youthful_valkyrie", 2], ["child_of_night", 2], ["vampire_nighthawk", 2], ["blood_artist", 2], ["indulgent_aristocrat", 2], ["spirit_link", 2], ["unearth", 2], ["gravedigger", 1], ["swords_to_plowshares", 1], ["pacifism", 1], ["wrath_of_god", 1]]) },
  kessa: { opponentId: "a2", name: "Kessa Emberhand", epithet: "the Stormcaller", colors: "UR", tier: 2, archetype: "control", decklist: d([["mountain", 8], ["island", 7], ["steam_vents", 2], ["young_pyromancer", 3], ["arc_mage", 2], ["man_o_war", 2], ["aether_channeler", 1], ["lightning_bolt", 3], ["shock", 2], ["blaze", 1], ["hordeling_outburst", 1], ["brainstorm", 2], ["boomerang", 2], ["essence_scatter", 2], ["counterspell", 1], ["air_elemental", 1]]) },
  maelin: { opponentId: "b2", name: "Adept Maelin", epithet: "the Pyre-Warden", colors: "BR", tier: 2, archetype: "aggro", decklist: d([["swamp", 8], ["mountain", 7], ["blood_crypt", 2], ["skirk_prospector", 2], ["raging_goblin", 2], ["goblin_piker", 2], ["hordeling_outburst", 2], ["goblin_grenade", 2], ["indulgent_aristocrat", 2], ["blood_artist", 2], ["unearth", 2], ["gravedigger", 2], ["gallows_djinn", 1], ["dark_ritual", 1], ["lightning_bolt", 1], ["terror", 1], ["siege_gang_commander", 1]]) },
  brennor: { opponentId: "c2", name: "Brennor of the Glade", epithet: "the Sanctuary", colors: "WG", tier: 2, archetype: "midrange", decklist: d([["forest", 9], ["plains", 6], ["temple_garden", 2], ["gladecover_scout", 3], ["blurred_mongoose", 2], ["birds_of_paradise", 2], ["soul_warden", 2], ["youthful_valkyrie", 2], ["rancor", 2], ["blanchwood_armor", 2], ["spirit_link", 2], ["giant_growth", 2], ["glorious_anthem", 1], ["swords_to_plowshares", 1], ["pacifism", 1], ["restoration_angel", 1]]) },
  pell: { opponentId: "e2", name: "Pell of the Shallows", epithet: "the Tidesower", colors: "UG", tier: 2, archetype: "control", decklist: d([["island", 7], ["forest", 6], ["breeding_pool", 2], ["evolving_wilds", 2], ["hedron_crab", 4], ["cathartic_adept", 2], ["traumatizer", 2], ["rampant_growth", 3], ["birds_of_paradise", 2], ["blurred_mongoose", 2], ["timberland_guide", 2], ["brainstorm", 2], ["essence_scatter", 2], ["counterspell", 1], ["altar_of_dementia", 1]]) },
  corvane: { opponentId: "d3", name: "Lord Corvane", epithet: "the Sepulchre", colors: "WB", tier: 3, archetype: "midrange", decklist: d([["plains", 7], ["swamp", 7], ["godless_shrine", 2], ["scrubland", 1], ["youthful_valkyrie", 2], ["inspiring_overseer", 2], ["indulgent_aristocrat", 2], ["blood_artist", 2], ["gravedigger", 2], ["unearth", 2], ["zombify", 2], ["restoration_angel", 1], ["serra_angel", 3], ["swords_to_plowshares", 2], ["pacifism", 1], ["dark_ritual", 1], ["terror", 1]]) },
  varro: { opponentId: "a3", name: "Varro Flamebrand", epithet: "the Ashwright", colors: "UR", tier: 3, archetype: "control", decklist: d([["island", 7], ["mountain", 7], ["steam_vents", 2], ["volcanic_island", 1], ["hedron_crab", 3], ["young_pyromancer", 2], ["arc_mage", 2], ["traumatizer", 2], ["lightning_bolt", 3], ["shock", 2], ["blaze", 1], ["brainstorm", 2], ["divination", 1], ["boomerang", 2], ["counterspell", 1], ["essence_scatter", 1], ["faerie_formation", 1]]) },
  sorrel: { opponentId: "b3", name: "High Warden Sorrel", epithet: "the Inquisitor", colors: "BR", tier: 3, archetype: "midrange", decklist: d([["swamp", 7], ["mountain", 7], ["blood_crypt", 2], ["badlands", 1], ["young_pyromancer", 3], ["arc_mage", 2], ["hypnotic_specter", 2], ["hymn_to_tourach", 1], ["duress", 2], ["mind_rot", 2], ["lightning_bolt", 3], ["shock", 2], ["blaze", 1], ["terror", 2], ["vampire_nighthawk", 1], ["dark_ritual", 1], ["unearth", 1]]) },
  ysolde: { opponentId: "c3", name: "Thornmother Ysolde", epithet: "the Thornmother", colors: "WG", tier: 3, archetype: "aggro", decklist: d([["forest", 8], ["plains", 6], ["temple_garden", 2], ["savannah", 1], ["savannah_lions", 2], ["suntail_hawk", 2], ["fencing_ace", 2], ["gladecover_scout", 2], ["blurred_mongoose", 2], ["birds_of_paradise", 2], ["raise_the_alarm", 2], ["glorious_anthem", 2], ["rancor", 2], ["blanchwood_armor", 2], ["giant_growth", 1], ["swords_to_plowshares", 1], ["serra_angel", 1]]) },
  quill: { opponentId: "e3", name: "Magister Quill", epithet: "the Drowned Grove", colors: "UG", tier: 3, archetype: "control", decklist: d([["forest", 7], ["island", 6], ["breeding_pool", 2], ["tropical_island", 1], ["evolving_wilds", 1], ["hedron_crab", 3], ["cathartic_adept", 2], ["traumatizer", 2], ["rampant_growth", 3], ["llanowar_elves", 2], ["man_o_war", 1], ["gaean_wurm", 2], ["pelakka_wurm", 1], ["baru_wurmspeaker", 1], ["altar_of_dementia", 2], ["essence_scatter", 2], ["counterspell", 1], ["brainstorm", 1]]) },
};
