/**
 * S18 director round (Chris, note 12): the card manifest with gold values — every pool card with its
 * current shop price (shopPrice: round(4 × (1 + mv))), prizeOnly flag, and a blank "proposed tier"
 * column for the card-by-card tiering audit Chris takes to the planner. Writes docs/card-price-manifest.md.
 *   pnpm tsx scripts/card-manifest.ts
 */
import { writeFileSync } from "node:fs";
import { loadCardPool } from "../packages/cards/src/loader.js";
import { shopPrice } from "../packages/world/src/shop.js";
import { defaultKnobs } from "../packages/world/src/knobs.js";
import { parseManaCost, manaValue } from "../packages/cards/src/mana.js";

const pool = loadCardPool("data/cards");
const knobs = defaultKnobs();
const rows: string[] = [];
const cards = [...pool.cards.values()].filter((d) => !d.id.startsWith("test_") && !d.isTokenDef);
const colourOf = (d: { manaCost?: string; colors?: string[] }) => (d.colors && d.colors.length ? d.colors.join("") : (d.manaCost ?? "").replace(/[^WUBRG]/g, "").split("").filter((c, i, a) => a.indexOf(c) === i).join("") || "C");
cards.sort((a, b) => colourOf(a).localeCompare(colourOf(b)) || manaValue(parseManaCost(a.manaCost ?? "")) - manaValue(parseManaCost(b.manaCost ?? "")) || a.name.localeCompare(b.name));
for (const d of cards) {
  const mv = manaValue(parseManaCost(d.manaCost ?? ""));
  const isBasic = d.types.includes("Land") && (d.supertypes ?? []).includes("Basic");
  const price = isBasic ? "free" : String(shopPrice(d, knobs));
  const flags = [d.prizeOnly ? "prizeOnly" : "", d.source === "custom" ? "custom" : ""].filter(Boolean).join(", ");
  rows.push(`| ${d.name} | ${colourOf(d)} | ${d.types.join(" ")}${d.subtypes?.length ? ` — ${d.subtypes.join(" ")}` : ""} | ${d.manaCost ?? "—"} | ${mv} | ${price} | ${flags} |  |`);
}
const out = `# Card price manifest (S18 director round, Chris's note 12)

*Generated by \`pnpm tsx scripts/card-manifest.ts\` — ${cards.length} pool cards (tokens and test cards excluded). Current shop price = round(shopPriceMultiplier × shopBasePrice × (1 + mana value)) = 4 × (1 + mv) at defaults; basics are free. \`prizeOnly\` cards never appear in shops (Black Lotus). The last column is for the card-by-card tiering audit (Chris + planner): which cards are shop-legal in which towns/rings, and at what multiplier — "spicier" cards (Hymn, Demonic Tutor, Bitterblossom, Baru, Wrath, Serra, Specter, Control Magic…) to be unavailable or dearer.*

| Card | Colour | Type | Cost | MV | Price (gold) | Flags | Proposed tier |
|---|---|---|---|---|---|---|---|
${rows.join("\n")}
`;
writeFileSync("docs/card-price-manifest.md", out);
console.log(`wrote docs/card-price-manifest.md (${cards.length} cards)`);
